### ISSUE TITLE
Runner stops after first iteration when no output fields are set

### ISSUE THREAD

**Issue by jreyesr** [jreyesr/insomnia-plugin-batch-requests#4]
Reported by @dotJson in #3

> I find if I dont set an output map in the batch dialog it does not iterate through the CSV so I have been selecting bogus fields to get it to go.
> if it, as you say should work without defining an output, then something is stopping my runners after the first iteration. I have been setting it to some random selection in the CSV headers and typing garbage in the JSON path field to get it to go.

**Comment by jreyesr** [comment]
Steps to reproduce:

1. Set up a request, include at least a placeholder template tag
2. Open the Batch Requests dialog, load a CSV file
3. ⚠ Don't set even one Output, this is what triggers the bug
4. Click the Run button

Result:

1. First request runs and the progress bar updates to 1/N
2. No more requests are sent afterwards
3. No error dialog is displayed
4. The DevTools console (shown by pressing `Ctrl+Alt+I`) prints a log: `The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

![image](https://user-images.githubusercontent.com/23390438/226206018-701910bd-d80a-4541-8506-e599f87f4889.png)

**Comment by jreyesr** [comment]
However, other times it does work correctly when no Outputs are set

![image](https://user-images.githubusercontent.com/23390438/226206631-4460c432-b076-49ef-97c2-344e85e29f3a.png)

**Comment by dotJson** [comment]
The stopping issue does appear to be related to XML in the response. Unfortunately I have to use the XML API for some calls.
 
![iteration2](https://user-images.githubusercontent.com/5536982/226215917-e8cae1f5-0ca9-414b-ad81-47dcff7aebbc.jpg)

**Comment by dotJson** [comment]
Also, I figured out the scenario a bit further. When API responds with XML, if you do not set outputs then it completes and halts after 1 iteration, and does not pop the alert about incorrect content-type. As if it halts before the alert call. However, if you set an output, the iterations do not stop but the alert pops. So it seems if allowing XML responses (by testing and bypassing any JSON evaluation?)  would enable iterations to continue without having to set outputs.

**Comment by jreyesr** [comment]
OK. It's definitely due to XML then.

Indeed, if you do not set any outputs, the check for Content-Type JSON does not trigger (in 3), but then it goes ahead and tries to parse the body as JSON anyways (in 5), and that's killing your process. If you set at least one output, it enters (3), gives an alert but then bypasses the rest of that iteration and doesn't even try to parse it as JSON.

![image](https://user-images.githubusercontent.com/23390438/226217891-f68f6c9d-956a-408e-b0eb-15a8a59c31fc.png)

That should be easy to fix, by changing that logic around a bit and only making it parse the response when both a) you have requested at least one output AND b) the response returns a JSON contenttype. That will forbid extracting any information from non-JSON responses, but as I understand it you don't need it anyway, you're just calling the API for its side effects.
